services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.wsgi:app
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key}
      - DATABASE_URL=sqlite:///instance/side_quest_dev.db
    volumes:
      # Mount source code for hot-reloading
      - ./src:/app/src
      - ./instance:/app/instance
      # Mount tests directory for running tests
      - ./tests:/app/tests
    restart: unless-stopped
    # Command to keep container running for development
    stdin_open: true
    tty: true 