version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/wsgi.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-production_secret_key}
      - DATABASE_URL=sqlite:///instance/side_quest.db
    volumes:
      - ./instance:/app/instance
    restart: always

  # Optional: Add additional services like a database, cache, etc.
  # Example for a PostgreSQL database:
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=sidequest
  #     - POSTGRES_PASSWORD=sidequest_password
  #     - POSTGRES_DB=sidequest_db
  #   restart: always

# volumes:
#   postgres_data:
