"""Initial migration

Revision ID: f7e0ff18a446
Revises: 
Create Date: 2025-04-07 12:00:49.957282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e0ff18a446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventurers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('experience_reward', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventurer_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['adventurer_id'], ['adventurers.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_completions')
    op.drop_table('quests')
    op.drop_table('adventurers')
    # ### end Alembic commands ###
