"""Create initial tables

Revision ID: b5f96772d59e
Revises: f7e0ff18a446
Create Date: 2025-04-07 16:34:40.147598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f96772d59e'
down_revision = 'f7e0ff18a446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_adventurers_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('auth_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('auth_token')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_adventurers_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
