[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "side_quest_py"
version = "0.1.0"
description = "A Python adventure quest project"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "python-ulid==3.0.0",
    # Add your runtime dependencies here
]

[project.optional-dependencies]
dev = [
    "black==23.3.0",
    "pylint==2.17.4",
    "mypy==1.3.0",
    "pytest==7.3.1"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 120

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "import-error",  # Temporarily disable import errors while we fix the structure
]

[tool.pylint.MASTER]
init-hook = """
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))
sys.path.append(str(Path(__file__).parent / 'src'))
"""

[tool.pylint.format]
max-line-length = 120

[tool.pylint.basic]
good-names = ["app", "db", "migrate", "config", "env"]

[tool.pylint.design]
max-args = 10
max-attributes = 15
max-branches = 20
max-locals = 20
max-parents = 7
max-public-methods = 20
max-returns = 6
max-statements = 50

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
mypy_path = "src"

[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
filterwarnings = [
    "ignore::DeprecationWarning:ast.*:"
]
pythonpath = [".", "src"]
